common:
  config:
    feature:
      flags:
        enableSMS: false

management:
  endpoints:
    web:
      exposure:
        include: ['health','info','env','beans','prometheus','refresh']
